In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.activations import linear, relu, sigmoid

In [2]:
df=pd.read_csv("C:\\Users\\redmi\\OneDrive\\Desktop\\INVICTA\\invicta-2022-level-2\\inv2_train.csv")

In [3]:
df

Id  Label      0      1      2      3      4      5      6      7  \
0      917     20  255.0  255.0  171.0  149.0  155.0  153.0  156.0  168.0   
1      754     17  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0   
2     1009     23  193.0  193.0  191.0  191.0  189.0  189.0  190.0  191.0   
3     1327     31    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4     1711     28  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0   
...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1195   679     15  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0   
1196   772     18  117.0  144.0  153.0  145.0  141.0   95.0  137.0  167.0   
1197   682     15  168.0  175.0  177.0  175.0  172.0  162.0  101.0   26.0   
1198  1136     25  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0   
1199   272      7  133.0  136.0  137.0  139.0  141.0  144.0  146.0  147.0   

      ...    774    775    776    777    778    779    780    781    782  \
0     ...  249.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0   
1     ...  181.0  246.0  255.0  254.0  255.0  255.0  255.0  255.0  255.0   
2     ...  197.0  198.0  200.0  197.0  201.0  201.0  202.0  202.0  202.0   
3     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4     ...   94.0   94.0   94.0   95.0  107.0  111.0  107.0  108.0  113.0   
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1195  ...  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0   
1196  ...  230.0  230.0  216.0  193.0  172.0  154.0  177.0  194.0  206.0   
1197  ...   41.0   44.0   44.0   48.0   49.0   57.0   53.0   60.0   63.0   
1198  ...  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0   
1199  ...  111.0   98.0   80.0   73.0   74.0   73.0   68.0   59.0   56.0   

        783  
0     255.0  
1     255.0  
2     205.0  
3       0.0  
4     104.0  
...     ...  
1195  255.0  
1196  204.0  
1197   61.0  
1198  255.0  
1199   51.0  

[1200 rows x 786 columns]

In [6]:
df['Label'].value_counts() 

28    132
34     60
33     49
18     43
25     43
15     40
29     39
7      38
12     37
3      36
23     35
24     35
27     35
14     34
2      33
17     33
11     32
19     32
6      31
26     30
10     30
32     29
9      27
13     27
20     26
0      25
8      24
16     24
31     24
30     22
5      22
4      20
21     19
22     18
1      16
Name: Label, dtype: int64

In [7]:
df.to_numpy()

array([[ 917.,   20.,  255., ...,  255.,  255.,  255.],
       [ 754.,   17.,  255., ...,  255.,  255.,  255.],
       [1009.,   23.,  193., ...,  202.,  202.,  205.],
       ...,
       [ 682.,   15.,  168., ...,   60.,   63.,   61.],
       [1136.,   25.,  255., ...,  255.,  255.,  255.],
       [ 272.,    7.,  133., ...,   59.,   56.,   51.]])

In [121]:
X=df.drop(['Id','Label'],axis=1)

X=X[0:1000]
X

0      1      2      3      4      5      6      7      8      9  \
0    255.0  255.0  171.0  149.0  155.0  153.0  156.0  168.0  151.0  153.0   
1    255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  209.0  170.0   
2    193.0  193.0  191.0  191.0  189.0  189.0  190.0  191.0  190.0  191.0   
3      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4    255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
995  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  254.0  255.0   
996    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
997   34.0   33.0   32.0   31.0   33.0   32.0   33.0   34.0   34.0   34.0   
998   95.0  100.0  108.0  116.0  101.0   95.0  106.0   96.0   87.0  108.0   
999  199.0  200.0  202.0  202.0  203.0  203.0  203.0  203.0  205.0  205.0   

     ...    774    775    776    777    778    779    780    781    782    783  
0    ...  249.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  
1    ...  181.0  246.0  255.0  254.0  255.0  255.0  255.0  255.0  255.0  255.0  
2    ...  197.0  198.0  200.0  197.0  201.0  201.0  202.0  202.0  202.0  205.0  
3    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    ...   94.0   94.0   94.0   95.0  107.0  111.0  107.0  108.0  113.0  104.0  
..   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
995  ...  253.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  
996  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
997  ...   42.0   49.0   54.0   53.0   51.0   48.0   49.0   49.0   51.0   53.0  
998  ...   83.0   79.0   78.0   85.0   90.0   78.0   79.0   70.0   72.0   88.0  
999  ...  120.0  116.0  120.0  117.0  135.0  172.0  171.0  171.0  172.0  167.0  

[1000 rows x 784 columns]

In [122]:
Y=pd.DataFrame(zip(df.Label))
Y=Y[0:1000]
Y

0
0    20
1    17
2    23
3    31
4    28
..   ..
995  28
996  28
997  12
998  18
999  10

[1000 rows x 1 columns]

In [123]:
# tf.random.set_seed(1234) # for consistent results
# model = Sequential(
#     [               
#         ### START CODE HERE ###
#         tf.keras.Input(shape=(784,)),
# #         Dense(units=784,activation='relu'),
# #         Dense(units=800,activation='relu'),
# #         Dense(units=500,activation='relu'),
# #         Dense(units=300,activation='relu'),
# #         Dense(units=100,activation='relu'),
#         Dense(units=5000,activation='relu'),
#         Dense(units=300,activation='relu'),
# #         Dense(units=9,activation='relu'),
#         Dense(units=3,activation='linear')

#         ### END CODE HERE ### 
#     ], name = "my_model" 
# )


In [124]:
# model.summary()

In [125]:
from tensorflow.keras import datasets, layers, models


In [157]:
cnn = models.Sequential([
    layers.Conv2D(filters=64, kernel_size=(2,2), activation='relu', input_shape=(28,28,1)),
    layers.MaxPooling2D((2,2)),
    
    layers.Conv2D(filters=64, kernel_size=(2,2), activation='relu'),
    layers.MaxPooling2D((2,2)),
    
    layers.Conv2D(filters=32, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    
#     layers.Conv2D(filters=32, kernel_size=(3,3), activation='relu'),
#     layers.MaxPooling2D((2,2)),
    
#     layers.Conv2D(filters=128, kernel_size=(3,3), activation='relu'),
#     layers.MaxPooling2D((2,2)),
    
    layers.Flatten(),
#     layers.Dense(128, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(32, activation='relu'),
#     layers.Dense(32, activation='relu'),
    layers.Dense(35, activation='softmax')
])

In [158]:
cnn.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [159]:
xn=X.to_numpy()
xn=xn.reshape(1000,28,28,1)

yn=Y.to_numpy().reshape(1000,1)
his=cnn.fit(xn,yn,epochs=300)


Epoch 1/300
32/32 [==============================] - 5s 38ms/step - loss: 4.4413 - accuracy: 0.0710
Epoch 2/300
32/32 [==============================] - 1s 36ms/step - loss: 3.5013 - accuracy: 0.1120
Epoch 3/300
32/32 [==============================] - 1s 36ms/step - loss: 3.4870 - accuracy: 0.1120
Epoch 4/300
32/32 [==============================] - 1s 43ms/step - loss: 3.4384 - accuracy: 0.1190
Epoch 5/300
32/32 [==============================] - 1s 42ms/step - loss: 3.3963 - accuracy: 0.1350
Epoch 6/300
32/32 [==============================] - 1s 43ms/step - loss: 3.3589 - accuracy: 0.1430
Epoch 7/300
32/32 [==============================] - 1s 40ms/step - loss: 3.3225 - accuracy: 0.1450
Epoch 8/300
32/32 [==============================] - 1s 41ms/step - loss: 3.3016 - accuracy: 0.1440
Epoch 9/300
32/32 [==============================] - 1s 41ms/step - loss: 3.3072 - accuracy: 0.1470
Epoch 10/300
32/32 [==============================] - 1s 41ms/step - loss: 3.2355 - accuracy: 0.1530

32/32 [==============================] - 2s 59ms/step - loss: 1.8688 - accuracy: 0.4640
Epoch 83/300
32/32 [==============================] - 2s 58ms/step - loss: 1.8576 - accuracy: 0.4720
Epoch 84/300
32/32 [==============================] - 2s 58ms/step - loss: 1.8184 - accuracy: 0.4760
Epoch 85/300
32/32 [==============================] - 2s 54ms/step - loss: 1.8441 - accuracy: 0.4630
Epoch 86/300
32/32 [==============================] - 2s 54ms/step - loss: 1.9650 - accuracy: 0.4570
Epoch 87/300
32/32 [==============================] - 2s 57ms/step - loss: 1.9333 - accuracy: 0.4330
Epoch 88/300
32/32 [==============================] - 2s 60ms/step - loss: 1.9048 - accuracy: 0.4410
Epoch 89/300
32/32 [==============================] - 2s 58ms/step - loss: 1.8591 - accuracy: 0.4760
Epoch 90/300
32/32 [==============================] - 2s 58ms/step - loss: 1.7445 - accuracy: 0.4980
Epoch 91/300
32/32 [==============================] - 2s 56ms/step - loss: 1.6940 - accuracy: 0.5120
Epo

32/32 [==============================] - 1s 38ms/step - loss: 1.4024 - accuracy: 0.5920
Epoch 163/300
32/32 [==============================] - 1s 37ms/step - loss: 1.3938 - accuracy: 0.5720
Epoch 164/300
32/32 [==============================] - 1s 36ms/step - loss: 1.7128 - accuracy: 0.5190
Epoch 165/300
32/32 [==============================] - 1s 37ms/step - loss: 1.5790 - accuracy: 0.5460
Epoch 166/300
32/32 [==============================] - 1s 41ms/step - loss: 1.3732 - accuracy: 0.6020
Epoch 167/300
32/32 [==============================] - 1s 41ms/step - loss: 1.3539 - accuracy: 0.6090
Epoch 168/300
32/32 [==============================] - 1s 40ms/step - loss: 1.2062 - accuracy: 0.6290
Epoch 169/300
32/32 [==============================] - 1s 40ms/step - loss: 1.1264 - accuracy: 0.6560
Epoch 170/300
32/32 [==============================] - 1s 41ms/step - loss: 1.1768 - accuracy: 0.6530
Epoch 171/300
32/32 [==============================] - 1s 41ms/step - loss: 1.1068 - accuracy: 0

32/32 [==============================] - 2s 57ms/step - loss: 0.9105 - accuracy: 0.7140
Epoch 243/300
32/32 [==============================] - 2s 57ms/step - loss: 0.8803 - accuracy: 0.7180
Epoch 244/300
32/32 [==============================] - 2s 55ms/step - loss: 0.8470 - accuracy: 0.7410
Epoch 245/300
32/32 [==============================] - 2s 55ms/step - loss: 0.8842 - accuracy: 0.7240
Epoch 246/300
32/32 [==============================] - 2s 53ms/step - loss: 1.0436 - accuracy: 0.6890
Epoch 247/300
32/32 [==============================] - 2s 55ms/step - loss: 0.9775 - accuracy: 0.6950
Epoch 248/300
32/32 [==============================] - 2s 58ms/step - loss: 0.9438 - accuracy: 0.7090
Epoch 249/300
32/32 [==============================] - 2s 59ms/step - loss: 0.9289 - accuracy: 0.7110
Epoch 250/300
32/32 [==============================] - 2s 58ms/step - loss: 1.0384 - accuracy: 0.6760
Epoch 251/300
32/32 [==============================] - 2s 57ms/step - loss: 1.0448 - accuracy: 0

In [150]:
# splitting for test

Xvt=df.drop(['Id','Label'],axis=1)
xtt=Xvt.to_numpy()
xtt=xtt[1000:1200]
xtt=xtt.reshape(200,28,28,1)

Yvt=pd.DataFrame(zip(df.Label))
ytt=Yvt.to_numpy()
ytt=ytt[1000:1200]
ytt=ytt.reshape(200,1)

In [151]:
cnn.evaluate(xtt,ytt)

7/7 [==============================] - 1s 18ms/step - loss: 19.3883 - accuracy: 0.1000


[19.388324737548828, 0.10000000149011612]

In [96]:
# model.compile(
#     loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True) , #sparsecategorical
# #     loss=tf.keras.losses.MeanSquaredError(),
#     optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),metrics=['accuracy']
# )
# # optimizer=tf.keras.optimizers.Adam(learning_rate=0.001)

# history = model.fit(
#     X,Y,
#     epochs=70
# )

In [97]:
dft=pd.read_csv("C:\\Users\\redmi\\OneDrive\\Desktop\\INVICTA\\invicta-2022-level-2\\inv2_test.csv")

In [98]:
dft

Id      0      1      2      3      4      5      6      7      8  ...  \
0     132  205.0  237.0  234.0  170.0  128.0  172.0  209.0  182.0  168.0  ...   
1    1546   30.0   30.0   32.0   29.0   31.0   34.0   31.0   28.0   28.0  ...   
2     424   58.0   63.0   67.0   69.0   69.0   71.0   73.0   73.0   73.0  ...   
3     380  224.0  223.0  224.0  224.0  224.0  224.0  224.0  224.0  225.0  ...   
4     767  224.0  224.0  225.0  225.0  225.0  225.0  225.0  225.0  225.0  ...   
..    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  ...   
557  1004  227.0  228.0  230.0  230.0  236.0  241.0  242.0  237.0  234.0  ...   
558  1687  123.0  139.0  125.0  151.0  136.0  141.0  114.0   65.0   70.0  ...   
559   576  233.0  232.0  232.0  232.0  231.0  229.0  235.0  169.0  144.0  ...   
560   534   22.0   13.0    0.0    1.0   32.0   30.0    0.0    1.0    1.0  ...   
561   411   61.0   71.0   81.0   65.0   33.0   25.0   30.0   83.0  103.0  ...   

       774    775    776    777    778    779    780    781    782    783  
0    112.0   92.0  155.0  133.0   56.0   57.0   66.0   43.0   39.0   72.0  
1     24.0   25.0   27.0   26.0   27.0   29.0   28.0   27.0   27.0   27.0  
2     66.0  118.0  138.0  140.0  162.0  176.0  165.0  152.0  147.0  147.0  
3    196.0  184.0  183.0  183.0  182.0  185.0  189.0  189.0  193.0  195.0  
4    218.0  200.0  199.0  195.0  194.0  197.0  200.0  197.0  203.0  205.0  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
557   77.0   75.0   96.0  146.0  177.0  191.0  203.0  211.0  212.0  221.0  
558  141.0  137.0  183.0  241.0  223.0  165.0  154.0  148.0  159.0  210.0  
559  103.0   78.0  115.0  153.0  198.0  214.0  219.0  220.0  219.0  221.0  
560    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0  
561  100.0   91.0  108.0   76.0   89.0  104.0  107.0  126.0  111.0  104.0  

[562 rows x 785 columns]

In [99]:
# 

In [100]:
dftest=dft.drop(['Id'],axis=1)


In [101]:
# test1=dftest.loc[0].to_numpy()

In [102]:
xtest=dftest.to_numpy()
xtest=xtest.reshape(562,28,28,1)


In [103]:
# prediction = model.predict(test1.reshape(1,784))
prediction=cnn.predict(xtest)

18/18 [==============================] - 0s 11ms/step


In [104]:
# np.argmax(prediction)
prediction


array([[1.06400599e-07, 6.21304324e-08, 7.46269885e-04, ...,
        7.62745971e-04, 1.00038555e-08, 3.01929703e-09],
       [1.82287518e-09, 3.65639297e-09, 7.18770181e-08, ...,
        2.87032500e-03, 2.30059374e-12, 3.18723353e-10],
       [3.49841593e-03, 3.48785965e-11, 3.10723335e-05, ...,
        5.52426167e-02, 3.98559230e-08, 2.94214464e-03],
       ...,
       [6.67347635e-08, 8.08426830e-06, 2.96297713e-07, ...,
        9.68731911e-06, 1.91690363e-02, 9.07934368e-01],
       [9.99794662e-01, 2.13385256e-12, 2.02849937e-09, ...,
        8.08238254e-10, 8.33136511e-13, 8.25227566e-16],
       [4.49453053e-09, 5.01580666e-10, 5.64879770e-07, ...,
        1.08789289e-04, 2.21650826e-05, 6.58389823e-08]], dtype=float32)

In [105]:
prediction[0]

array([1.06400599e-07, 6.21304324e-08, 7.46269885e-04, 7.35290384e-10,
       2.35762715e-10, 4.91802288e-09, 3.80362314e-03, 4.50574942e-02,
       2.02432826e-09, 5.68693181e-08, 6.67797303e-06, 5.68608637e-04,
       1.02501102e-02, 2.29263901e-06, 2.68691732e-03, 3.97814716e-07,
       2.59234789e-09, 5.05821995e-10, 6.73358858e-01, 2.25308846e-04,
       4.37427894e-04, 2.38211384e-09, 1.04103640e-06, 5.85975977e-06,
       3.12798392e-08, 3.63474227e-02, 2.41595861e-02, 2.01577455e-01,
       1.05886329e-06, 4.39536691e-08, 3.82604611e-07, 1.60602369e-07,
       7.62745971e-04, 1.00038555e-08, 3.01929703e-09], dtype=float32)

In [106]:
prediction[1]

array([1.82287518e-09, 3.65639297e-09, 7.18770181e-08, 1.78843045e-15,
       1.01165005e-08, 8.93003289e-08, 8.18760881e-09, 7.87913138e-12,
       1.26696614e-04, 1.04057840e-09, 3.74045417e-09, 5.92286941e-16,
       4.38797478e-08, 1.53131102e-11, 7.27684948e-13, 3.88532698e-07,
       1.24158427e-19, 2.68214673e-04, 1.26074639e-12, 4.12989718e-15,
       1.16399137e-19, 1.13650012e-05, 2.42254959e-15, 2.00216036e-15,
       1.43517864e-08, 1.93475413e-19, 2.48399527e-14, 1.67062670e-18,
       9.92745697e-01, 4.93160945e-17, 4.93049438e-12, 3.97697045e-03,
       2.87032500e-03, 2.30059374e-12, 3.18723353e-10], dtype=float32)

In [107]:
# data = {'Id':[],'Label':[]}
# final=pd.DataFrame(data)
# final
# for i in range(0,534):
#   testpic=dftest.loc[i].to_numpy()
#   prediction = model.predict(test1.reshape(1,784))




In [108]:
list_predict_label=[]
# list_predict_id=[]

In [109]:
for i in range(0,562):
#   testpic=dftest.loc[i].to_numpy() #dftest
#   prediction = model.predict()
  ithpredict_label=prediction[i]
  predict_label=np.argmax(ithpredict_label)
#   predict_id=dft_label[0,i]
  list_predict_label.append(predict_label)
#   list_predict_id.append(predict_id)





In [110]:
# data = {'Id':list_predict_id,'Label':list_predict_label}
dft_id={'Label':list_predict_label}
finaltemp=pd.DataFrame(dft_id)
final=pd.DataFrame(zip(dft.Id,finaltemp.Label))
final


0   1
0     132  18
1    1546  28
2     424  12
3     380  15
4     767  28
..    ...  ..
557  1004  15
558  1687  28
559   576  34
560   534   0
561   411   7

[562 rows x 2 columns]

In [111]:
# dict = {'0': 'Id',
#         '1': 'Label',
#        }
 
# # call rename () method
# final.rename(columns=dict,
#           inplace=True)

# final.columns.values[0:2] =["Id", "Label" ]

final = final.rename({0: 'Id', 1: 'Label'}, axis=1)
final

Id  Label
0     132     18
1    1546     28
2     424     12
3     380     15
4     767     28
..    ...    ...
557  1004     15
558  1687     28
559   576     34
560   534      0
561   411      7

[562 rows x 2 columns]

In [112]:
final['Label'].value_counts() 

28    93
34    39
18    31
33    29
15    25
29    22
10    21
7     19
31    18
2     17
25    17
23    16
32    15
24    15
13    14
11    14
14    14
3     13
6     12
21    11
16    11
12    11
8     10
5      9
0      8
4      8
27     8
1      7
20     6
9      6
19     6
17     6
26     5
22     4
30     2
Name: Label, dtype: int64

In [113]:
final.to_csv("C:\\Users\\redmi\\OneDrive\\Desktop\\INVICTA\\invicta-2022-level-2\\results\\lvl2_3.csv")